base_path = "."

# NOTE: Keep in sync with lit-localize.json
locales = [
  "ar",
  "ca",
  "de",
  "es",
  "fr",
  "id",
  "it",
  "ja",
  "ko",
  "pl",
  "pt_BR",
  "ru",
  "th",
  "tr",
  "vi",
]

branches = [
  "master",
]

[[paths]]
  reference = "src/static/_locales/en/messages.json"
  l10n = "src/static/_locales/{android_locale}/messages.json"

[[paths]]
  reference = "cws/en/listing-description.lang"
  l10n = "cws/{android_locale}/listing-description.lang"

[[paths]]
  reference = "src/lit-locales/source/es.xlf"
  l10n = "src/lit-locales/source/{android_locale}.xlf"
